### ISSUE TITLE
Build fails with undefined: http2.TrailerPrefix under Go 1.27 — go.mod pins golang.org/x/net v0.54.0

### ISSUE THREAD

**Issue by svenXY** [LeonAdato/xk6-output-statsd#43]
**Environment**
- Extension version: v0.2.3
- k6 build tool: xk6 (any recent image)
- Go toolchain: go1.27
- k6 core: v1.7.1 (via `go.k6.io/k6`)

**Steps to reproduce**
```bash
xk6 build --with github.com/LeonAdato/xk6-output-statsd
```

**Expected**
Build succeeds.

**Actual**
```
# google.golang.org/grpc/internal/transport
/home/xk6/go/pkg/mod/google.golang.org/grpc@v1.80.0/internal/transport/handler_server.go:271:18: undefined: http2.TrailerPrefix
```

**Root cause**
This extension's `go.mod` pins `golang.org/x/net` at `v0.54.0` and `google.golang.org/grpc` at `v1.80.0` as indirect dependencies. That forces Go's minimal version selection to `x/net v0.54.0` for the whole build, even though k6 core itself only requires `v0.49.0`.

`x/net v0.54.0` temporarily dropped `http2.TrailerPrefix` under the `go1.27` build tag (see [[golang/go#79503](https://github.com/golang/go/issues/79503)](https://github.com/golang/go/issues/79503)); it was restored in `v0.55.0`. `grpc-go` still calls that symbol internally, so any build using Go 1.27 and resolving `x/net` at exactly this extension's pinned version fails.

**Suggested fix**
Run `go get -u ./... && go mod tidy` (or at minimum bump `golang.org/x/net` to `>= v0.55.0`) to unpin the indirect dependency and let it float to a Go-1.27-compatible version.

**Workaround** (for anyone hitting this before it's fixed)
```bash
xk6 build --with github.com/LeonAdato/xk6-output-statsd --replace golang.org/x/net=golang.org/x/net@v0.55.0
```

**Comment by LeonAdato** [comment]
Just updated to version 0.2.5 - check me and see if this resolves the issue.

**Comment by svenXY** [comment]
unfortunately not:

[...]
Using Kubernetes executor with image grafana/xk6 ...
[...]

<details>
<summary>$ xk6 build --with github.com/LeonAdato/xk6-output-statsd still fails with thesamme error message:</summary>

```
$ xk6 build --with github.com/LeonAdato/xk6-output-statsd --verbose
2026-08-28T09:44:16Z DBG Resolving k6 module from extension dependencies (version: latest)
2026-08-28T09:44:16Z DBG Resolving k6 module from extension dependencies count=1
2026-08-28T09:44:16Z DBG Checking extension go.mod for k6 dependency module=github.com/LeonAdato/xk6-output-statsd
2026-08-28T09:44:16Z DBG No version specified for extension, resolving latest module=github.com/LeonAdato/xk6-output-statsd
2026-08-28T09:44:16Z DBG Go proxy request url=https://proxy.golang.org/github.com/!leon!adato/xk6-output-statsd/@latest
2026-08-28T09:44:16Z DBG Go proxy response url=https://proxy.golang.org/github.com/!leon!adato/xk6-output-statsd/@latest status=200
2026-08-28T09:44:16Z DBG Resolved latest version for extension module=github.com/LeonAdato/xk6-output-statsd version=v0.2.5
2026-08-28T09:44:16Z DBG Go proxy request url=https://proxy.golang.org/github.com/!leon!adato/xk6-output-statsd/@v/v0.2.5.mod
2026-08-28T09:44:16Z DBG Go proxy response url=https://proxy.golang.org/github.com/!leon!adato/xk6-output-statsd/@v/v0.2.5.mod status=200
2026-08-28T09:44:16Z DBG Found k6 dependency in extension extension=github.com/LeonAdato/xk6-output-statsd k6module=go.k6.io/k6/v2 k6version=v2.0.0
2026-08-28T09:44:16Z DBG Resolved k6 module repo=go.k6.io/k6/v2 version=v2.0.0
2026-08-28T09:44:16Z INF Building new k6 binary (native)
2026-08-28T09:44:17Z INF Initializing Go module
go: creating new go.mod: module k6
2026-08-28T09:44:17Z INF Creating k6 main
2026-08-28T09:44:17Z INF adding dependency go.k6.io/k6/v2@v2.0.0
go: downloading go.k6.io/k6/v2 v2.0.0
go: downloading github.com/mattn/go-colorable v0.1.14
go: downloading github.com/mattn/go-isatty v0.0.22
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading github.com/Masterminds/semver/v3 v3.5.0
go: downloading github.com/fatih/color v1.19.0
go: downloading github.com/grafana/k6provider v0.5.0
go: downloading github.com/mstoykov/envconfig v1.5.0
go: downloading github.com/spf13/cobra v1.4.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/crypto/x509roots/fallback v0.0.0-20260413170323-a8e9237a216b
go: downloading golang.org/x/crypto v0.50.0
go: downloading golang.org/x/term v0.42.0
go: downloading gopkg.in/guregu/null.v3 v3.3.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/stretchr/testify v1.11.1
go: downloading golang.org/x/sys v0.43.0
go: downloading go.opentelemetry.io/otel/trace v1.43.0
go: downloading golang.org/x/time v0.15.0
go: downloading go.opentelemetry.io/otel v1.43.0
go: downloading github.com/spf13/afero v1.1.2
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/gorilla/websocket v1.5.3
go: downloading github.com/prometheus/client_golang v1.23.2
go: downloading github.com/grafana/k6-cloud-openapi-client-go v0.0.2
go: downloading github.com/grafana/xk6-dashboard-assets v0.1.2
go: downloading github.com/pkg/browser v0.0.0-20240102092130-5ac0b6a4141c
go: downloading github.com/r3labs/sse/v2 v2.10.0
go: downloading github.com/tidwall/gjson v1.18.0
go: downloading github.com/grafana/sobek v0.0.0-20260429085637-a66d4790012b
go: downloading golang.org/x/net v0.53.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.43.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.43.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.43.0
go: downloading go.opentelemetry.io/otel/sdk v1.43.0
go: downloading github.com/influxdata/influxdb1-client v0.0.0-20190402204710-8ff2fc3824fc
go: downloading github.com/klauspost/compress v1.18.5
go: downloading github.com/mstoykov/atlas v0.0.0-20220811071828-388f114305dd
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.43.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v1.43.0
go: downloading go.opentelemetry.io/otel/metric v1.43.0
go: downloading go.opentelemetry.io/otel/sdk/metric v1.43.0
go: downloading google.golang.org/grpc v1.80.0
go: downloading go.opentelemetry.io/proto/otlp v1.10.0
go: downloading google.golang.org/protobuf v1.36.11
go: downloading buf.build/gen/go/prometheus/prometheus/protocolbuffers/go v1.36.11-20260331160422-eae785f0a21d.1
go: downloading github.com/prometheus/client_model v0.6.2
go: downloading github.com/serenize/snaker v0.0.0-20201027110005-a7ad2135616e
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading go.uber.org/goleak v1.3.0
go: downloading github.com/andybalholm/brotli v1.2.1
go: downloading github.com/mccutchen/go-httpbin/v2 v2.20.0
go: downloading golang.org/x/text v0.36.0
go: downloading gopkg.in/validator.v2 v2.0.1
go: downloading github.com/prometheus/common v0.66.1
go: downloading gopkg.in/cenkalti/backoff.v1 v1.1.0
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.1
go: downloading github.com/Azure/go-ntlmssp v0.1.1
go: downloading github.com/Soontao/goHttpDigestClient v0.0.0-20170320082612-6d28bb1415c5
go: downloading github.com/google/uuid v1.6.0
go: downloading github.com/evanw/esbuild v0.28.0
go: downloading github.com/go-sourcemap/sourcemap v2.1.4+incompatible
go: downloading github.com/bufbuild/protocompile v0.14.1
go: downloading github.com/golang/protobuf v1.5.4
go: downloading github.com/PuerkitoBio/goquery v1.12.0
go: downloading github.com/dlclark/regexp2 v1.12.0
go: downloading github.com/google/pprof v0.0.0-20260115054156-294ebfa9ad83
go: downloading github.com/go-logr/logr v1.4.3
go: downloading github.com/go-logr/stdr v1.2.2
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20260401024825-9d38bb4040a9
go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.28.0
go: downloading buf.build/gen/go/gogo/protobuf/protocolbuffers/go v1.36.11-20240617172848-e1dbca2775a7.1
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.3.0
go: downloading github.com/prometheus/procfs v0.16.1
go: downloading github.com/onsi/ginkgo v1.16.5
go: downloading github.com/onsi/gomega v1.39.1
go: downloading github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
go: downloading github.com/nu7hatch/gouuid v0.0.0-20131221200532-179d4d0c4d8d
go: downloading github.com/chromedp/cdproto v0.0.0-20250803210736-d308e07a266d
go: downloading github.com/go-json-experiment/json v0.0.0-20250211171154-1ae217ad3535
go: downloading golang.org/x/sync v0.20.0
go: downloading github.com/jhump/protoreflect v1.18.0
go: downloading github.com/andybalholm/cascadia v1.3.3
go: downloading go.opentelemetry.io/auto/sdk v1.2.1
go: downloading github.com/cenkalti/backoff/v5 v5.0.3
go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.4.0
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20260401024825-9d38bb4040a9
go: downloading go.yaml.in/yaml/v2 v2.4.2
go: downloading github.com/chromedp/sysutil v1.1.0
go: downloading github.com/nxadm/tail v1.4.11
go: downloading github.com/jhump/protoreflect/v2 v2.0.0-beta.1
go: downloading gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
go: downloading github.com/google/go-cmp v0.7.0
go: downloading github.com/kr/pretty v0.3.1
go: downloading github.com/xyproto/randomstring v1.0.5
go: downloading github.com/kylelemons/godebug v1.1.0
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/rogpeppe/go-internal v1.14.1
go: downloading go.yaml.in/yaml/v3 v3.0.4
go: downloading gonum.org/v1/gonum v0.17.0
go: downloading github.com/petermattis/goid v0.0.0-20260113132338-7c7de50cc741
go: finding module for package github.com/fsnotify/fsnotify
go: finding module for package gopkg.in/tomb.v1
go: downloading github.com/fsnotify/fsnotify v1.10.1
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: found gopkg.in/tomb.v1 in gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: found github.com/fsnotify/fsnotify in github.com/fsnotify/fsnotify v1.10.1
2026-08-28T09:44:41Z INF importing extensions
2026-08-28T09:44:41Z INF adding dependency github.com/LeonAdato/xk6-output-statsd
go: downloading github.com/LeonAdato/xk6-output-statsd v0.2.5
go: downloading github.com/DataDog/datadog-go v4.8.3+incompatible
go: downloading github.com/Microsoft/go-winio v0.6.2
go: downloading github.com/stretchr/objx v0.1.1
go: downloading golang.org/x/sys v0.44.0
go: downloading golang.org/x/crypto v0.51.0
go: downloading golang.org/x/term v0.43.0
go: downloading gopkg.in/guregu/null.v3 v3.5.0
go: downloading github.com/spf13/afero v1.9.5
go: downloading golang.org/x/net v0.54.0
go: downloading golang.org/x/text v0.37.0
2026-08-28T09:44:57Z INF Building k6
# google.golang.org/grpc/internal/transport
/home/xk6/go/pkg/mod/google.golang.org/grpc@v1.80.0/internal/transport/handler_server.go:271:18: undefined: http2.TrailerPrefix
2026-08-28T09:46:13Z INF Cleaning up work directory /tmp/k6foundry3105419125
2026-08-28T09:46:13Z ERR compiling: executing go command: exit status 1
```

</details>

**Comment by travis-reed** [comment]
Confirming this is still broken on the current released version, and that the fix appears to already be on `main` — it just hasn't been tagged.

**Still failing with the latest tag (v0.2.5):**

```
docker run --rm --platform linux/amd64 --entrypoint sh grafana/xk6 \
  -c 'cd /tmp && xk6 build --with github.com/LeonAdato/xk6-output-statsd'

# google.golang.org/grpc/internal/transport
/home/xk6/go/pkg/mod/google.golang.org/grpc@v1.80.0/internal/transport/handler_server.go:271:18:
undefined: http2.TrailerPrefix
```

`@latest` resolves to `v0.2.5`, whose `go.mod` still carries `golang.org/x/net v0.54.0 // indirect` — the version identified above as the problem.

**Works when built from `main`:**

```
docker run --rm --platform linux/amd64 --entrypoint sh grafana/xk6 \
  -c 'cd /tmp && xk6 build --with github.com/LeonAdato/xk6-output-statsd@main'

INF Successful build platform=linux/amd64
INF added module=go.k6.io/k6/v2 version=v2.2.0
INF added module=github.com/LeonAdato/xk6-output-statsd version=v0.2.6-0.20260827205942-057e6b6cc6cc
k6 v2.2.0 (go1.27.0, linux/amd64)
```

Worth noting I only tested the single-extension build above — a build combining this with other extensions could still resolve `x/net` differently.

For anyone else hitting this, a third workaround alongside the `--replace` above is pinning the builder image instead, which keeps you on a Go 1.26 toolchain: `grafana/xk6:1.4.11`.
